### ISSUE TITLE
Can not use TTL checks

### ISSUE THREAD

**Issue by nnothing1** [kitex-contrib/registry-consul#16]
**Describe the bug**
不能在 api.AgentServiceCheck 使用 TTL
https://github.com/kitex-contrib/registry-consul/blob/8dbf48a297ac4973791db62208632f62902d30d0/consul_registry.go#L125
主要是这里强制开启了 TCP check, 开启 TCP check 就必须设置 Inverval > 0， 但是在 consul 中 Interval 和 TTL 不能同时设置。
```shell
error="Invalid check: Interval and TTL cannot both be specified"
```
假如我同时开启 TTL 和 Interval 就会报错， 不开 Interval 只开 TTL 就会因为上述代码强制开启了 TCP checks 报错， 让我设置 Interval 大于 0。
```shell
error="Invalid check: Interval must be > 0 for Script, HTTP, H2PING, TCP, UDP or OSService checks"
```

同时好像也没有实现关于 TTL checks 的 UpdateTTL 相关逻辑， 希望能够实现对 TTL checks支持。

**Comment by baiyutang** [comment]
你好。你描述的问题的确是的。但是你说的自定义TTL check 的可以通过  WithCheck 实现。如果想 UpdateTTL  当下只能自己实例化一个 consul 调用 UpdateTTL 去做。可以去尝试。如果对你们使用场景不友好，欢迎PR
