### ISSUE TITLE
服务注册时使用了tags，但注册后在consul的meta里

### ISSUE THREAD

**Issue by booldesign** [kitex-contrib/registry-consul#6]
我服务注册时使用了tags，但注册后在consul的meta里
```
func localOption() []server.Option {
	r, err := consul.NewConsulRegister(util.ConsulAddr())
	if err != nil {
		panic(err)
	}
	address, err := net.ResolveTCPAddr("tcp", constant.ServicesAccountServiceAddr)
	if err != nil {
		panic(err)
	}
	return []server.Option{
		server.WithSuite(trace.NewDefaultServerSuite()),
		server.WithServerBasicInfo(&rpcinfo.EndpointBasicInfo{ServiceName: constant.ServicesAccountServiceName}),
		server.WithRegistry(r),
		server.WithRegistryInfo(&registry.Info{
			Addr:        address,
			ServiceName: constant.ServicesAccountServiceName,
			StartTime:   time.Now(),
			Tags: map[string]string{
				"version": "1.0",  // 这边注册tag
			}}),
		server.WithServiceAddr(address),
		server.WithLimit(&limit.Option{MaxConnections: constant.MaxConnections, MaxQPS: constant.MaxQPS}),
	}
}
```
在consul的后台，发现在meta里
![image](https://user-images.githubusercontent.com/12163931/226573956-ce8bf579-7b49-4900-96f5-b57f5754e600.png)

看了[registry-consul](https://github.com/kitex-contrib/registry-consul/blob/main/consul_registry.go#L93)代码，tag也是当meta使用的

**Comment by li-jin-gou** [comment]
cc @baiyutang

**Comment by li-jin-gou** [comment]
![image](https://user-images.githubusercontent.com/97824201/226592649-a8c93482-f68e-4291-8b49-f18d4bda114c.png)
我看到代码实现是这样的，不知道这里是否可以设置到 tags

**Comment by Dup4** [comment]
我猜可能是因为 consul 的 [注册服务接口](https://developer.hashicorp.com/consul/api-docs/agent/service#register-service) 里的 [Tags](https://developer.hashicorp.com/consul/api-docs/agent/service#tags) 字段是一个 `array<string>`，而 [Meta](https://developer.hashicorp.com/consul/api-docs/agent/service#meta) 是 `map<string|string>`。

**Comment by baiyutang** [comment]
明天确定下回复两位

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by lilaoba123** [comment]
> 
我也发现了这个问题，tag注册进去了，但服务发现不能指定到某个tag
